name: rusquant_todo_app_dev_v1
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  retrofit_generator: ^8.1.0
  dio: ^5.4.3+1
  get: ^4.6.6
  json_annotation: ^4.9.0
  retrofit: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.10
  freezed: ^2.5.2
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
